name: CD deploy to VDS

on:
  workflow_run:
    workflows: [ "CI build" ]
    types: [ completed ]
    branches: [ "main" ]

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/0.0.${{ github.run_number }}',
              sha: context.sha
            })